spring:
  cloud:
    function:
      definition: acmeRideshareHrEmployeeCreatedConsumer;acmeRideshareHrEmployeeCreatedDtoSupplier
    stream:
      bindings:
        acmeRideshareHrEmployeeCreatedConsumer-in-0:
          destination: acme/rideshare/hr/employee/created
        acmeRideshareHrEmployeeCreatedDtoSupplier-out-0:
          destination: acme/rideshare/hr/employee/created/dto
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'localhost:55555'
                msgVpn: default
                clientUsername: default
                clientPassword: default
    vault:
      host: 192.168.100.121
      port: 8200
      scheme: http
      uri: http://localhost:8200
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: s.uCKxN7Kyd3sXknzATm4vH7uv
      fail-fast: true
      config:
        lifecycle:
          enabled: true
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: '*'

